import { TaskEntity } from "../../entities/task/model/task";

export const mockTasks: TaskEntity[] = [
  {
    id: "1",
    isCompleted: false,
    title: "Verification page",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    isCompleted: false,
    title: "Dropdown for 'My Profile'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    isCompleted: false,
    title: "Modal for 'Creat new task'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    isCompleted: false,
    title: "Modal for 'Update task'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    isCompleted: false,
    title: "Dialog for 'Delete task'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    isCompleted: false,
    title: "Drop down for 'Sort'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    isCompleted: false,
    title: "Drop down for 'Filter'",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    isCompleted: false,
    title: "Verification page",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "9",
    isCompleted: false,
    title: "Fix container for main sections",
    dueDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
